name: Build and Release

on:
  push:
    tags: ['v*'] # Parte solo quando crei un tag (es. v1.0)

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install libcurl4-openssl-dev
      
      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          make
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ping-lib-${{ matrix.os }}
          path: build/ping_tool